language: en

pipeline:
  - name: "botwhitespace_tokenizer.BotWhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 5
  - name: "DIETClassifier"
    entity_recognition: true
    epochs: 200
    constrain_similarities: True
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100
    constrain_similarities: True
    retrieval_intent: faq
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
